# PR builds only

sudo: false
language: ruby

install: bundle install
script: bundle exec jekyll serve

matrix:
  include:
    - rvm: 2.6.0-preview3
    - rvm: 2.5.3
    - rvm: 2.4.5
    - rvm: 2.3.8

notfications:
  email: false
